---
- name: defining target group
  hosts: web-servers
  #defining variables 
  vars:
    x: httpd
    z: git
  #become means sudo access /root access
  become: true
  tasks:
  - name: testing ping module 
    ping: 

  - name: running sample commands
    command: date

  - name: Insatalling {{x}} and {{z}} software in target amazon linux machine
    yum: 
      name:
      - "{{x}}"
      - "{{z}}"
      state: present 
  - name: copy code to http app server location
    copy:
      src: myapps/index.html
      dest: /var/www/html/gsk.html

  - name: starting {{x}} service
    service: 
      name: "{{x}}"
      state: started