name: gsk job
#trigger point
on: 
  push:
    branches: [ "main" ]  
    paths-ignore:
      - "README.md"
      - "terraform.tfstate"

# creating jobs 
jobs:
  infra-provision-job:
    runs-on: ubuntu-latest
    steps: 
    #calling first github action to clone my git repo dryrun to runner machine
    - name: taking code from my repo
      uses: actions/checkout@v5
      with:
        ref: main

    - name: installing terraform
      uses: hashicorp/setup-terraform@v3

    - name: my first step to test github action
      run: |
           echo "Hello WOrld"
           git version
           whoami
           ls -a
           terraform version  
    # configure AWS creds  
    - name: connecting to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: verify aws connection 
      run: |
        echo "checking with command"
        aws s3 ls 
    - name: deploy terraform resources
      run: |
        echo "implementing terraform deals"
        terraform init 
        terraform plan 
        sleep 2
        terraform apply --auto-approve
        ls modules/ec2
    #creating artifact and uploading ansible inventory file
    - name: uploading ansoble inventory to github artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gsk-github-artifact
        path: modules/ec2/ansible-inventory.txt

  infra-destroy-job:
    needs: infra-provision-job
    runs-on: ubuntu-latest
    steps:
    - name: checking out code
      uses: actions/checkout@v5
      with:
        ref: main
    - name: login to aws creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2

    #downloading artifact the one I created above
    - name: downloading ansible inventory artifact
      uses: actions/download-artifact@v5
      with: 
        name: gsk-github-artifact

    #listing artifact
    - name: Display structure of downloaded files
      run: ls -R

    #installing
    - name: installing terraform
      uses: hashicorp/setup-terraform@v3

      #destroying 
    - name: destroy terraform
      run: |
        echo "destroying aws job"
        terraform init
        terraform state list
        terraform destroy --auto-approve


